(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(connection-local-criteria-alist
   '(((:application eshell :protocol "ssh" :user "flocks" :machine
					"134.122.90.60")
	  autogenerated-connection-local-profile/\(:application\ eshell\ :protocol\ \"ssh\"\ :user\ \"flocks\"\ :machine\ \"134.122.90.60\"\))
	 ((:application eshell) eshell-connection-default-profile)
	 ((:application tramp :protocol "flatpak")
	  tramp-container-connection-local-default-flatpak-profile)
	 ((:application tramp)
	  tramp-connection-local-default-system-profile
	  tramp-connection-local-default-shell-profile)))
 '(connection-local-profile-alist
   '((autogenerated-connection-local-profile/\(:application\ eshell\ :protocol\ \"ssh\"\ :user\ \"flocks\"\ :machine\ \"134.122.90.60\"\)
	  (eshell-path-env-list "/bin" "/usr/bin" "/sbin" "/usr/sbin"
							"/usr/local/bin" "/usr/local/sbin"))
	 (eshell-connection-default-profile (eshell-path-env-list))
	 (tramp-container-connection-local-default-flatpak-profile
	  (tramp-remote-path "/app/bin" tramp-default-remote-path "/bin"
						 "/usr/bin" "/sbin" "/usr/sbin"
						 "/usr/local/bin" "/usr/local/sbin"
						 "/local/bin" "/local/freeware/bin"
						 "/local/gnu/bin" "/usr/freeware/bin"
						 "/usr/pkg/bin" "/usr/contrib/bin" "/opt/bin"
						 "/opt/sbin" "/opt/local/bin"))
	 (tramp-connection-local-darwin-ps-profile
	  (tramp-process-attributes-ps-args "-acxww" "-o"
										"pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
										"-o" "state=abcde" "-o"
										"ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args")
	  (tramp-process-attributes-ps-format (pid . number)
										  (euid . number)
										  (user . string)
										  (egid . number) (comm . 52)
										  (state . 5) (ppid . number)
										  (pgrp . number)
										  (sess . number)
										  (ttname . string)
										  (tpgid . number)
										  (minflt . number)
										  (majflt . number)
										  (time . tramp-ps-time)
										  (pri . number)
										  (nice . number)
										  (vsize . number)
										  (rss . number)
										  (etime . tramp-ps-time)
										  (pcpu . number)
										  (pmem . number) (args)))
	 (tramp-connection-local-busybox-ps-profile
	  (tramp-process-attributes-ps-args "-o"
										"pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
										"-o" "stat=abcde" "-o"
										"ppid,pgid,tty,time,nice,etime,args")
	  (tramp-process-attributes-ps-format (pid . number)
										  (user . string)
										  (group . string) (comm . 52)
										  (state . 5) (ppid . number)
										  (pgrp . number)
										  (ttname . string)
										  (time . tramp-ps-time)
										  (nice . number)
										  (etime . tramp-ps-time)
										  (args)))
	 (tramp-connection-local-bsd-ps-profile
	  (tramp-process-attributes-ps-args "-acxww" "-o"
										"pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
										"-o"
										"state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args")
	  (tramp-process-attributes-ps-format (pid . number)
										  (euid . number)
										  (user . string)
										  (egid . number)
										  (group . string) (comm . 52)
										  (state . string)
										  (ppid . number)
										  (pgrp . number)
										  (sess . number)
										  (ttname . string)
										  (tpgid . number)
										  (minflt . number)
										  (majflt . number)
										  (time . tramp-ps-time)
										  (pri . number)
										  (nice . number)
										  (vsize . number)
										  (rss . number)
										  (etime . number)
										  (pcpu . number)
										  (pmem . number) (args)))
	 (tramp-connection-local-default-shell-profile
	  (shell-file-name . "/bin/sh") (shell-command-switch . "-c"))
	 (tramp-connection-local-default-system-profile
	  (path-separator . ":") (null-device . "/dev/null"))))
 '(custom-safe-themes
   '("120daecf822f5af47ec6c03ea654e722ff86135970a3b5d774f12f329f930bb5"
	 "d9a947788a4c5f7051c4ad3a3e0e9d76218209899683d3e9ed1e2aa6cd10d462"
	 "9d8d60e69db09062e759f008e59fac1d76618b09cddaf06cef093653c16f1e75"
	 "4c33bd6d84f2155c63aca2f49b6564f616030e32bddef1cf41e34ff70a4f3eb2"
	 "c65bb1da475c39c0638f75cf704d5d5a578920196f3ff323ed75de7363f269e2"
	 "7758a8b8912ef92e8950a4df461a4d510484b11df0d7195a8a3d003965127abc"
	 "e410458d3e769c33e0865971deb6e8422457fad02bf51f7862fa180ccc42c032"
	 "ed1b7b4db911724b2767d4b6ad240f5f238a6c07e98fff8823debcfb2f7d820a"
	 "0af489efe6c0d33b6e9b02c6690eb66ab12998e2649ea85ab7cfedfb39dd4ac9"
	 "be84a2e5c70f991051d4aaf0f049fa11c172e5d784727e0b525565bb1533ec78"
	 "f943bbe619c11a066be5ed60111f3846e7e31af7a376a3fbc02596387f92cae7"
	 "0c5d7ffa7cdf8b889342d2cd38f6ddd2cc716561048feca89b17fda56677d6b8"
	 "4594d6b9753691142f02e67b8eb0fda7d12f6cc9f1299a49b819312d6addad1d"
	 "0d9028987183602b113c27e52e549b2eeb23fb29ebfc19ca0b6612fa57472066"
	 "159a29ab0ec5ba4e2811eddd9756aa779b23467723dcbdd223929fbf2dde8954"
	 "cd191949417eafc21b1cb9f3c03f0af6f75f404a7fcd83e886556a0ce7c157af"
	 "b216e9b72dc8c2b702e4fcfd3c0af2d73c87eba46fd4db824ddb50863447d6a9"
	 "f12083eec1537fc3bf074366999f0ee04ab23ab3eaba57614785d88b9db2a5d4"
	 "9f27d5afd6d78b40bf1290c10722818e0b90f141fc3758d3c2d284ccb565de15"
	 "cdad4e5bc718111deb1f1a2a35e9781e11724144a1eb2064732c337160946760"
	 "7776ba149258df15039b1f0aba4b180d95069b2589bc7d6570a833f05fdf7b6d"
	 "4ade6b630ba8cbab10703b27fd05bb43aaf8a3e5ba8c2dc1ea4a2de5f8d45882"
	 "296f12a58b5bc587fdf08995a84cb8cdec74b83b794fddaad012e520c411ddf1"
	 "3325e2c49c8cc81a8cc94b0d57f1975e6562858db5de840b03338529c64f58d1"
	 "8bd9efaae59e6d32620212d237d4c6a944627e464bb8a4c79aca8455fa8bc7dc"
	 "404a0697bbf4247fb558be5c97f0f8729da054b3aea709ef945124b1c7d3fd3d"
	 "a47adf806dc2c70a9bdf67b51dc8eb9b171ef94d0c2a8e489cbd232cc059acbb"
	 "8ad1730991fcbe6b9780a743397eacfb53f99811ab7170cf6b6d28c99fa67adf"
	 "d693c76c4177db783cec6cc1de64412c6c1593f40ad40106feb7fe6ed38d0168"
	 "a923c3f60cd0237121fb3ba0cddbbe630f12a52091b9d9d99e5e5ce9685f24dd"
	 "569f33960d9d639e780ace5dcc2bfa834d4d7fad2084c147a9b1d86138e3014e"
	 "53de110617756b339d746835924912c562871e81d48c2bfc59290582cc33f2bf"
	 "2f687e0768a724518a2ea4ae9ef37fad9c2bfbeb03e9ca8dcfed8a73e1e6b0fc"
	 "0fed8ee2d4afeb46a9b5f5cc6a5344439597d013a06bcc4776fa9ef9b241ad7a"
	 "62eacfd7dd818757c3e605ef1ee8b2625434c631ca9940a05b1bf5f556be02f4"
	 "34cf3305b35e3a8132a0b1bdf2c67623bc2cb05b125f8d7d26bd51fd16d547ec"
	 "6ec30b2c5a8cbe35fa36a86cd4c8c7e1472e0f03ba3f010131cbf8b3c8ec334f"
	 "38b1ce862047bb599b519037a03a4c1a0660c40704a59f5056629f9494897c3e"
	 "302f8ffc6c53ba91fadc87e560f5978ea103bb1f8ccda3dc9b361a8a0bb91a74"
	 "99801fadb5e32fd32ff4fe95d57db39638fb26a81197aa1898d41f36c0e0d5d6"
	 "9e466654cdd23b7094627e49a39a99f2b369d7eda59e34002823b693e18305a7"
	 "3d359dc20fc259631d0079a6535da1f5e6205971a1e8501f7fa9271f6f9a71fc"
	 "eb3141ffdf8f8070f447e51b085ef4d1e6074c47e9cae84b103a9256dca9ed56"
	 "30526ab3507de50fd504df6d7ccff2fd9a564999f831ead500f0a10b1fe43053"
	 "8122fb61548fe36171d9cf24cdb9b5f24d053b626d4cda739c3815e080623209"
	 "d8bcb88ef0a3259a38d6deba78e569c0750ebfede82ad3e6da16573419fef48c"
	 "e27c9668d7eddf75373fa6b07475ae2d6892185f07ebed037eedf783318761d7"
	 "3454885b915a176dce4b53e35053b7ee0aa9362fb9e934057ac44b6842a97453"
	 "e8ab68ce371f48623dab9658d7910458e98affec3e09585a39552dbd3fd1ecda"
	 "d31c3706f7c1b0520405c796b33f515bc481d2062cbc964f3c36925665999a6d"
	 "d9c038dc91688c433de8e83709449563ec6475b900a21d7016856035ae4dcd32"
	 "f84dbe5cfa80aa6774c57fef30d76bcdeb71bd0077665fb74f75728c42f5675d"
	 "65a1a112abd99456167df57ce2cfff42ed137c4f9146e75b2ae9812499689c3a"
	 "ed6e47baf355da248c4de8953058234b82c8f838fc85f570f9fe1700e47b9426"
	 "cc0ea29f3e80c5c622cea5fd83686dd36963a9abcde5b21dfe6cee653b67d72f"
	 "454e92bc5f22f690afce91cb6f92a3ccb638c57a89e84c55759fb16dfb2444e4"
	 "6c01b5d4faa0f143055e63c9fba8e23e9160f181e54b14b46d56410811edbc9e"
	 "9e1cf0f16477d0da814691c1b9add22d7cb34e0bb3334db7822424a449d20078"
	 "046a2b81d13afddae309930ef85d458c4f5d278a69448e5a5261a5c78598e012"
	 "565c31b3d2fc6aa6292d0a2cd101ba1a059af254f46424b17f877b7814b79d74"
	 "5fecf6cc7c203ac54aeb1623ebc8012381eea1e4427c6d86cb6548dd023b2734"
	 "8c7e832be864674c220f9a9361c851917a93f921fedb7717b1b5ece47690c098"
	 "00cec71d41047ebabeb310a325c365d5bc4b7fab0a681a2a108d32fb161b4006"
	 "014cb63097fc7dbda3edf53eb09802237961cbb4c9e9abd705f23b86511b0a69"
	 "af74555caf764197ce1534b6da1847f99fea05332240b60947e4bcb9a1cacfcf"
	 "5306a83397853b49ec2ef1dc2ce417b4c9f5a3f4dad2deb21a19424479c98190"
	 "949dced57bf1176a3c18382e45e5340eb95a42fa2bf7278939e7c5b963388344"
	 "499fa10f9cbc4f70627bb52d7d8741ffe653d3a3d502fb082b2bcb4601348c7e"
	 "f1ec043b7c6b4b1e085e176d0548aaf73f5ccfda093c52ed2f444ccb803b9852"
	 "7d10fe203079c8252133d76ebac3f7b306914a7205e8df0e490479ca0aa96e40"
	 "fd2c6edaa0547670b038d650611e60786aae04c69123f63b5614c0d3c2576d7d"
	 "1b48bb548f19c725fb7bc1801786c1af1b7001d3565de151276754ee7dd0dce2"
	 "de32d907a31a725e1a59f4be9ff5196d01f0532d9e857dd6b2b3927231a3d4f8"
	 "871b064b53235facde040f6bdfa28d03d9f4b966d8ce28fb1725313731a2bcc8"
	 "3ca84532551daa1b492545bbfa47fd1b726ca951d8be29c60a3214ced30b86f5"
	 "5014b68d3880d21a5539af6ef40c1e257e9045d224efb3b65bf0ae7ff2a5e17a"
	 "8d11daa5f67b21b377f159f12b47074e3dc706d03aa42dce90203f4516041448"
	 "ee77d69f78a1a17dcd141a58367fb5534dfdb07e94924a10a03c54190bb6a0ef"
	 "779aa194815bd4f88b672856961077bc3c735cb82d05b440e981bd218749cf18"
	 "d445c7b530713eac282ecdeea07a8fa59692c83045bf84dd112dd738c7bcad1d"
	 "032426ec19e515fd3a54b38016a1c5e4ec066be3230198cb3df82d05630a02ed"
	 "9225db6c746ab38bdfe14af45aaf0549dc9d6bca73ffe81fd9e955f843d2e095"
	 "02f57ef0a20b7f61adce51445b68b2a7e832648ce2e7efb19d217b6454c1b644"
	 "d13b6ae136b853bc69c036009b6290f546e6c9c7ad026f60b0ce2a4f9a943d5f"
	 "7b8f5bbdc7c316ee62f271acf6bcd0e0b8a272fdffe908f8c920b0ba34871d98"
	 "5f8cd5196811710aac845319711cba9d87529db58e8b0f4c99ef934cad45ea58"
	 "b3ef09ed89ce20cfad8db3271ac5e8ba33901125b386df4476922ca9e6908174"
	 "ce4234c32262924c1d2f43e6b61312634938777071f1129c7cde3ebd4a3028da"
	 "97d6a04f01bf6385ad53d9bb1f39988cc631f2ba586e1984b4cfa988c61f6c26"
	 "23a8b2526bbbb6e90fc87ade10e466fc1f1f72b87497896677f5e86cc9d1d398"
	 "e2095cd2350502ac3dc68350f0a27485f1edb99b6fc40a782618e1d35bf9d079"
	 "9cb0bf79b7da7051d73338397991c5e331ae18ccdd9e5f301ccb6f53bece6227"
	 "e6a7b628460ea9c569228b3368fe0a8d11c615eeb4a0dccd253dbf548e63a835"
	 "3884928c24609bb9ca4b40e637b94b96f389f9175d5372e2f8a0d3549b556006"
	 "1a3c10fc7fa10f814aa59833271eb4f547fe5b0b47a95482477c5df75b9375c5"
	 "d067a9ec4b417a71fbbe6c7017d5b7c8b961f4b1fc495cd9fbb14b6f01cca584"
	 "57fbc89697ba2e93d7fa5efc1c37a8ff305d5ff39b1fe815291e311d49bf2d41"
	 "4f9dcade45eafffc375812e3b13af5c3e9404089fcf9db21224a0fdfae911873"
	 "33876ef6caf9c4cb35f8bc9430fb64ba503036a4e80532bb764edec121900248"
	 "e16cd3e6093cf35e65dbac6c7649931936f32f56be34477cb7cbe1ee332c5b99"
	 "e4013fb0675182b04aa22f29054842db418d5a72da7ebb3c5b9dbb624502aaec"
	 "eb7cd622a0916358a6ef6305e661c6abfad4decb4a7c12e73d6df871b8a195f8"
	 "11873c4fbf465b956889adfa9182495db3bf214d9a70c0f858f07f6cc91cbd47"
	 "84c2c93ce268699838b51eeeaaec46e064d5048e232b39113b73209be3ef6fd4"
	 "27fc6293ab3eaafd57703df8552d4e1629649a0f2266f107d8c9157956ce4d4b"
	 "1dbbf33c64f2fa781b0f68494c0edee535d3a9f0c7e106b047d21c719c779a30"
	 "1479377d38b49d40dba561b2e4ab354b78cedb721bd62e0210ca18652760d219"
	 "4d16802de4686030ed8f30b5a844713d68edec9cc07322bef54493d15e68d8cd"
	 "6454421996f0508c38215a633256e36c19a28591542fb0946cfc40f1dceb89cf"
	 "e9aa348abd3713a75f2c5ba279aa581b1c6ec187ebefbfa33373083ff8004c7c"
	 "3ab376acffab6b4e79ae2b6e0a1cce3fa21dbac0027f0ff0dfef02b5c838dba9"
	 "99cacbd48c5e315930dae7144a9b9d285b58d9ebd06b48dcc3b62f11dc051ffe"
	 "7c9da9df5b0b8c56be09a9a41ea5218d0fddc9019db773e5167cad31c6dd13c9"
	 "b00f762e269f7de455651384e13dadb584f7d366d3801354269f0ce4131af8dd"
	 "ae7ffd67c75705c76dcfd66fa212abdcdd62ab5be2635371b31dc4de13f40668"
	 "e405944a54b99c11463edddeb9ff4f8dd981cd2ae14a4b58458536c451323381"
	 "7e068da4ba88162324d9773ec066d93c447c76e9f4ae711ddd0c5d3863489c52"
	 "e3b2bad7b781a968692759ad12cb6552bc39d7057762eefaf168dbe604ce3a4b"
	 "25c9807d70ac15057821f8b830ac93a80ca2b2beca6f1e9e7f77cbc5578e21b4"
	 "56044c5a9cc45b6ec45c0eb28df100d3f0a576f18eef33ff8ff5d32bac2d9700"
	 "8a98116c38a1455f30b7963f771f152e6ca4979f1dba44d7d924c684846ef3c7"
	 "83ce78add4890eed936e7e3bf66cb74d4cf583310c3ef15e46c001ccae001050"
	 "0bc864218de42740db1822ab36e138d8d182fff40aec728c18ba690ed5d9d3f8"
	 "3552bb109b685cddd3ddf039bbdabd52595bc1ab2173d5e73e490c80eea47029"
	 "8aa77197f9e81285d348ef2ada129df45a2e690b745afb79a106b1096857e4b6"
	 "800b7247f1db93d1821f243ecd0417fd9a620e805a476be7b262ba7f8d0ff1fd"
	 "7a6cccfe4ff6a7fc5da04b56438732d46133af8b9d349fde9c025aead36e0d07"
	 "64bf4ceacb3986ef96e7e2730c4f947b086d5b62ba19d8b96a89325c5660fed9"
	 "da75eceab6bea9298e04ce5b4b07349f8c02da305734f7c0c8c6af7b5eaa9738"
	 "eff6aabe4be18b849c15481fba01a209550330546573542f7e3c2234fd7d7412"
	 "a56e8b3325891ea0c34f7c88b2978d29533b679a8a87cfaa4a337a818db8002d"
	 "c76f7055d55fb546147f2967cd659471b7c29e1acbc480ce15fbe0829b60adeb"
	 "2a3da9d4f818158dbf2528d0db2530cbf8c62f6b425e008d18a6eff0888c1d26"
	 "5809b3c3c6f71ce0a5bae1bf84a4cbbd85a562b53460392c36b79f8bed60b3b8"
	 "24e856ac77923f7b05905e6c5e4384a61071539b31e10f296bc145ad775bef93"
	 "2fe72e320104693d3d118e6c6d349d64d1e4a2c90d4ce0ac055ab3695f7e6544"
	 "e3743b74d4763f7c645ecb77ad8c8c39eb36e1609a7a7d63dfe9ff78e0d61f47"
	 "16463aca7ca5d861e03a6a5b0c0b2930492af491de081a9ab50f09d7fbbf7ef3"
	 "279f74e365ba5aade8bc702e0588f0c90b5dee6cf04cf61f9455661700a6ebeb"
	 "2dd4951e967990396142ec54d376cced3f135810b2b69920e77103e0bcedfba9"
	 "38e3a5e4f2ab8169ba4219e5fcd15d0b07067a759abf8a15525f17d87aa526f5"
	 "1cae4424345f7fe5225724301ef1a793e610ae5a4e23c023076dc334a9eb940a"
	 "5a1fd979d77df7a628a6d7c3770ca7a6086b132da7a655d5c7864b05be56dde1"
	 "b6d5e39149c9b3f3f8108e0bda88db49408a9058af2813e11416752279f2c426"
	 "ab64fe30895c281c0a1e4bb091d1038f903f520dec3e947aa16a06503ff93879"
	 "22fea3a596de3d8558bd1ceb5344a5ec1df20abc7c906677180a59bd737b5a51"
	 "48440b79470f7ea212375737b8da9b9c34b95c0c981bbf0d83c99c1cb4665c24"
	 "9d70d35ce321f20bb1dfbc9e6dcfeaaefb233fd1b9782c393aa20063d43d2091"
	 "b1a691bb67bd8bd85b76998caf2386c9a7b2ac98a116534071364ed6489b695d"
	 "5b5adc8b44a8a79e671b4c12c39f2640e8fe3cab473ee51456f33fccea05f7ef"
	 "94422cceb6b73ec604f974fd87bd526131ae3701879f03bde2bd8a047208795e"
	 "8d8207a39e18e2cc95ebddf62f841442d36fcba01a2a9451773d4ed30b632443"
	 "6945dadc749ac5cbd47012cad836f92aea9ebec9f504d32fe89a956260773ca4"
	 "5b9a45080feaedc7820894ebbfe4f8251e13b66654ac4394cb416fef9fdca789"
	 "636b135e4b7c86ac41375da39ade929e2bd6439de8901f53f88fde7dd5ac3561"
	 "0c08a5c3c2a72e3ca806a29302ef942335292a80c2934c1123e8c732bb2ddd77"
	 "b54376ec363568656d54578d28b95382854f62b74c32077821fdfd604268616a"
	 "251ed7ecd97af314cd77b07359a09da12dcd97be35e3ab761d4a92d8d8cf9a71"
	 "512ce140ea9c1521ccaceaa0e73e2487e2d3826cc9d287275550b47c04072bc4"
	 "e3daa8f18440301f3e54f2093fe15f4fe951986a8628e98dcd781efbec7a46f2"
	 "adaf421037f4ae6725aa9f5654a2ed49e2cd2765f71e19a7d26a454491b486eb"
	 "467dc6fdebcf92f4d3e2a2016145ba15841987c71fbe675dcfe34ac47ffb9195"
	 "169272064635ec628fe5c43853862e2a1d87e19702665bac941d4298dd19c5fd"
	 "3fe1ebb870cc8a28e69763dde7b08c0f6b7e71cc310ffc3394622e5df6e4f0da"
	 "944d52450c57b7cbba08f9b3d08095eb7a5541b0ecfb3a0a9ecd4a18f3c28948"
	 "bf948e3f55a8cd1f420373410911d0a50be5a04a8886cabe8d8e471ad8fdba8e"
	 "8d3ef5ff6273f2a552152c7febc40eabca26bae05bd12bc85062e2dc224cde9a"
	 "2721b06afaf1769ef63f942bf3e977f208f517b187f2526f0e57c1bd4a000350"
	 "aec7b55f2a13307a55517fdf08438863d694550565dee23181d2ebd973ebd6b8"
	 "1a1ac598737d0fcdc4dfab3af3d6f46ab2d5048b8e72bc22f50271fd6d393a00"
	 "7a424478cb77a96af2c0f50cfb4e2a88647b3ccca225f8c650ed45b7f50d9525"
	 "7435c097e5d051fa34ad58bf94ac1b2d5d1e14e62fd20dfedf2bb4403b09a446"
	 "8566e9107b01de614891b9b397c6f5b66ce2d328fd8f04770260c58c62c0c2b8"
	 "3a7f53a0268877716d309d37ea952533391420bf139c38f69752d1494341151a"
	 "ef8c33cc2730745d62d08ae0e5fedd018bb70129a4ec75f942e6d7996252295c"
	 "7360aba98b0e94dd1499fcba50534dd42976dfd50a25f5cf122e6b8f3e53c511"
	 "fefb102e277edbf63698d3994ec8b89ed1d75711a302ea05f095297f0e71f353"
	 "3199be8536de4a8300eaf9ce6d864a35aa802088c0925e944e2b74a574c68fd0"
	 "72ed8b6bffe0bfa8d097810649fd57d2b598deef47c992920aef8b5d9599eefe"
	 "d80952c58cf1b06d936b1392c38230b74ae1a2a6729594770762dc0779ac66b7"
	 "88f19534c13fe8a05c33bc03852f6d586d2bb5292dd2f93bc8f99727f71b4467"
	 "ae0fcd3896dc3f937483234a7874818fdeeca7a919ecb5a5ab7b5563d9f9c957"
	 "0e44755893f9ff825802c493cded385b1839165c4f094bad72a95125236a5797"
	 "ce409d3a932171747b7b8b7edafdc70b4614beb31a7204aa25517d7c0ab80c48"
	 "01f52ed4dc9cfd4f397eda57c9eb5fea360bd6c18a2684121cc47279bfca5a51"
	 "183dfa34e360f5bc2ee4a6b3f4236e6664f4cfce40de1d43c984e0e8fc5b51ae"
	 "22c213e81a533c259127302ef1e0f2d1f332df83969a1f9cf6d5696cbe789543"
	 "9dbd2c6f93cc1774c261f23042be8bf7decc8f6599c21189c04d7791231b2b79"
	 "931ee45708e894d5233fc4a94ae0065c765c1a0aeb1bd8d9feee22f5622f44b4"
	 "d2b7abf3fb8e9505a478a04bd6d727a029cab49d58c0fafe271293d095438067"
	 "5ca9d0a5971e42ecee31398533e5b9dfc01c61a69bf3fd69395aa189c792252e"
	 "c01cd0485ce35cf0a19ab91146d2c2b6528ec60ad4c8ffec5b2b7cc4bc05bd80"
	 "4e7672ce1015731d9d6955652f8f1b438420f109d15f662a014fa4e992429b9a"
	 "45611797b789abf53e97c43b29c7f10dd6f18971e238e700bc885e702531053a"
	 "935cd704a3b4b12c9c0582da1d25437e2802d0f82c5d46de0eb5a968dfad08da"
	 "3680500faf3f5707fdf16c123c32c74a44c388318e5054bb7ef8b7025158f469"
	 "046e442b73846ae114d575a51be9edb081a1ef29c05ae5e237d5769ecfd70c2e"
	 "0657bbbdf081bafc0b56d4d40cb333829eb576c8c519c8028f29afbf9559eb35"
	 "347313c47366c3cb305fb63dff7df87426061d5529a86c215086fe8581228733"
	 "b330e75c3717166db3a8a41eb180c705b46b97c584dffdb917b310f86025c811"
	 "9ae0e81ced7c8d587cb1db9fcb528856315d352822082518884e8726fe681d1d"
	 "ebcb78e41027f498a1ee53cd4ae41ebbf4c44841fe0ed787affd01ba5013c66b"
	 "9b7d703afa15e320af9aa6b3e02bb1ebb8657c23043f7054357f86ce014b5461"
	 "d983956f195a1a5e920c78216e6c164f4fd73a4fdce3f532d527182409f96515"
	 "83fc7ca4d73cee934d2a96d5f2f6fe243afede055497528ab89dbb92c1145020"
	 default))
 '(dashub--notify-delay 60)
 '(safe-local-variable-values
   '((etags-regen-ignores "test/manual/etags/")
	 (etags-regen-regexp-alist
	  (("c" "objc") "/[ \11]*DEFVAR_[A-Z_ \11(]+\"\\([^\"]+\\)\"/\\1/"
	   "/[ \11]*DEFVAR_[A-Z_ \11(]+\"[^\"]+\",[ \11]\\([A-Za-z0-9_]+\\)/\\1/"))
	 (vc-prepare-patches-separately) (vc-git-annotate-switches . "-w")
	 (diff-add-log-use-relative-names . t)))
 '(smtpmail-smtp-server "smtp.gmail.com" t)
 '(smtpmail-smtp-service 587 t)
 '(tab-bar-show nil)
 '(tab-width 4)
 '(warning-suppress-log-types '((comp))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(fringe ((t :background "unspecified-bg")))
 '(window-divider ((t :background "unspecified-bg" :foreground "unspecified-bg")))
 '(window-divider-first-pixel ((t :background "unspecified-bg" :foreground "unspecified-bg")))
 '(window-divider-last-pixel ((t :background "unspecified-bg" :foreground "unspecified-bg"))))
