* my dotfiles

** Initial setup

*** private env
I use a ~/.private file that I never commit and that contains some
private bash env variables I want to source. My zshrc source a file
~/.private so I create an empty one to avoid error.

#+BEGIN_SRC bash
  touch ~/.private
#+END_SRC

*** zsh

Switch from bash to zsh
#+BEGIN_SRC bash
  chsh -s $(which zsh)
#+END_SRC


** Install packages

*** YAY
Install `yay` the AUR package manager for arch, it automatically
fallbacks to pacman when the target package is not an AUR package and
it has the same CLI interface.

#+BEGIN_SRC bash
  bash ~/dotfiles/packages/install-yay.sh
#+END_SRC

*** Packages
I try to maintain a list of all the packages that I'm using, even if I
need to clean it up. I get the list of packages I installed
explicitely with

#+BEGIN_SRC bash
  pacman -Qeq > packages.list
#+END_SRC

Install all the packages from the list:

#+BEGIN_SRC bash
  bash ~/dotfiles/packages/install-packages.sh
#+END_SRC

#+BEGIN_SRC bash
  git clone git@github.com:flocks/st.git
  cd st
  make
  sudo make install
#+END_SRC

I prefer to compile emacs myself, so I can use any configuration flag
I may want. So far I'm only using --with-native-compilation

#+BEGIN_SRC bash
  bash ~/dotfiles/packages/install-emacs.sh
#+END_SRC


** Config files


#+BEGIN_SRC bash
  stow scripts
  stow i3
  stow git
  stow emacs
  stow nvim
  stow sxhkd
  stow kitty
  stow polybar
  stow --dotfiles prompt
  stow --dotfiles path
  stow --dotfiles xinit
  stow --dotfiles xmodmap
  stow --dotfiles zsh
#+END_SRC

** TODO
clean and add vim config
