set preview_images True
set draw_borders True
set column_ratios 1,2
map bg shell ln -fs %d/%f ~/dotfiles/wallpapers/current.png && feh --bg-scale ~/dotfiles/wallpapers/current.png

map gd cd ~/Downloads
map gw cd ~/wallpapers
map gc cd ~/dotfiles
map gm cd ~/music
map gl cd ~/ledger
map gvf cd ~/ledger/ledger-vault-front

